// 来源 https://github.com/MWeiLiu/Cascader-jobCategory-data

const jobCategory = [{
  'value': 100000,
  'label': '技术',
  'children': [{
    'value': 100100,
    'label': '后端开发',
    'children': [{
      'value': 100101,
      'label': 'Java',
    }, {
      'value': 100102,
      'label': 'C++',
    }, {
      'value': 100103,
      'label': 'PHP',
    }, {
      'value': 100104,
      'label': '数据挖掘',
    }, {
      'value': 100105,
      'label': 'C',
    }, {
      'value': 100106,
      'label': 'C#',
    }, {
      'value': 100107,
      'label': '.NET',
    }, {
      'value': 100108,
      'label': 'Hadoop',
    }, {
      'value': 100109,
      'label': 'Python',
    }, {
      'value': 100110,
      'label': 'Delphi',
    }, {
      'value': 100111,
      'label': 'VB',
    }, {
      'value': 100112,
      'label': 'Perl',
    }, {
      'value': 100113,
      'label': 'Ruby',
    }, {
      'value': 100114,
      'label': 'Node.js',
    }, {
      'value': 100115,
      'label': '搜索算法',
    }, {
      'value': 100116,
      'label': 'Golang',
    }, {
      'value': 100117,
      'label': '自然语言处理',
    }, {
      'value': 100118,
      'label': '推荐算法',
    }, {
      'value': 100119,
      'label': 'Erlang',
    }, {
      'value': 100120,
      'label': '算法工程师',
    }, {
      'value': 100121,
      'label': '语音/视频/图形开发',
    }, {
      'value': 100122,
      'label': '数据采集',
    }],
  }, {
    'value': 100200,
    'label': '移动开发',
    'children': [{
      'value': 100201,
      'label': 'HTML5',
    }, {
      'value': 100202,
      'label': 'Androvalue',
    }, {
      'value': 100203,
      'label': 'iOS',
    }, {
      'value': 100204,
      'label': 'WP',
    }, {
      'value': 100205,
      'label': 'web前端',
    }, {
      'value': 100206,
      'label': 'Flash',
    }, {
      'value': 100208,
      'label': 'JavaScript',
    }, {
      'value': 100209,
      'label': 'U3D',
    }, {
      'value': 100210,
      'label': 'COCOS2DX',
    }],
  }, {
    'value': 100300,
    'label': '测试',
    'children': [{
      'value': 100301,
      'label': '测试工程师',
    }, {
      'value': 100302,
      'label': '自动化测试',
    }, {
      'value': 100303,
      'label': '功能测试',
    }, {
      'value': 100304,
      'label': '性能测试',
    }, {
      'value': 100305,
      'label': '测试开发',
    }, {
      'value': 100306,
      'label': '移动端测试',
    }, {
      'value': 100307,
      'label': '游戏测试',
    }, {
      'value': 100308,
      'label': '硬件测试',
    }, {
      'value': 100309,
      'label': '软件测试',
    }],
  }, {
    'value': 100400,
    'label': '运维/技术支持',
    'children': [{
      'value': 100401,
      'label': '运维工程师',
    }, {
      'value': 100402,
      'label': '运维开发工程师',
    }, {
      'value': 100403,
      'label': '网络工程师',
    }, {
      'value': 100404,
      'label': '系统工程师',
    }, {
      'value': 100405,
      'label': 'IT技术支持',
    }, {
      'value': 100406,
      'label': '系统管理员',
    }, {
      'value': 100407,
      'label': '网络安全',
    }, {
      'value': 100408,
      'label': '系统安全',
    }, {
      'value': 100409,
      'label': 'DBA',
    }],
  }, {
    'value': 100500,
    'label': '数据',
    'children': [{
      'value': 100506,
      'label': 'ETL工程师',
    }, {
      'value': 100507,
      'label': '数据仓库',
    }, {
      'value': 100508,
      'label': '数据开发',
    }, {
      'value': 100509,
      'label': '数据挖掘',
    }, {
      'value': 100511,
      'label': '数据分析师',
    }, {
      'value': 100512,
      'label': '数据架构师',
    }, {
      'value': 100513,
      'label': '算法研究员',
    }],
  }, {
    'value': 100600,
    'label': '项目管理',
    'children': [{
      'value': 100601,
      'label': '项目经理',
    }, {
      'value': 100602,
      'label': '项目主管',
    }, {
      'value': 100603,
      'label': '项目助理',
    }, {
      'value': 100604,
      'label': '项目专员',
    }, {
      'value': 100605,
      'label': '实施顾问',
    }, {
      'value': 100606,
      'label': '实施工程师',
    }, {
      'value': 100607,
      'label': '需求分析工程师',
    }],
  }, {
    'value': 100800,
    'label': '硬件开发',
    'children': [{
      'value': 100801,
      'label': '硬件',
    }, {
      'value': 100802,
      'label': '嵌入式',
    }, {
      'value': 100803,
      'label': '自动化',
    }, {
      'value': 100804,
      'label': '单片机',
    }, {
      'value': 100805,
      'label': '电路设计',
    }, {
      'value': 100806,
      'label': '驱动开发',
    }, {
      'value': 100807,
      'label': '系统集成',
    }, {
      'value': 100808,
      'label': 'FPGA开发',
    }, {
      'value': 100809,
      'label': 'DSP开发',
    }, {
      'value': 100810,
      'label': 'ARM开发',
    }, {
      'value': 100811,
      'label': 'PCB工艺',
    }, {
      'value': 100812,
      'label': '模具设计',
    }, {
      'value': 100813,
      'label': '热传导',
    }, {
      'value': 100814,
      'label': '材料工程师',
    }, {
      'value': 100815,
      'label': '精益工程师',
    }, {
      'value': 100816,
      'label': '射频工程师',
    }],
  }, {
    'value': 100900,
    'label': '前端开发',
    'children': [{
      'value': 100901,
      'label': 'web前端',
    }, {
      'value': 100902,
      'label': 'Javascript',
    }, {
      'value': 100903,
      'label': 'Flash',
    }, {
      'value': 100904,
      'label': 'HTML5',
    }],
  }, {
    'value': 101000,
    'label': '通信',
    'children': [{
      'value': 101001,
      'label': '通信技术工程师',
    }, {
      'value': 101002,
      'label': '通信研发工程师',
    }, {
      'value': 101003,
      'label': '数据通信工程师',
    }, {
      'value': 101004,
      'label': '移动通信工程师',
    }, {
      'value': 101005,
      'label': '电信网络工程师',
    }, {
      'value': 101006,
      'label': '电信交换工程师',
    }, {
      'value': 101007,
      'label': '有线传输工程师',
    }, {
      'value': 101008,
      'label': '无线射频工程师',
    }, {
      'value': 101009,
      'label': '通信电源工程师',
    }, {
      'value': 101010,
      'label': '通信标准化工程师',
    }, {
      'value': 101011,
      'label': '通信项目专员',
    }, {
      'value': 101012,
      'label': '通信项目经理',
    }, {
      'value': 101013,
      'label': '核心网工程师',
    }, {
      'value': 101014,
      'label': '通信测试工程师',
    }, {
      'value': 101015,
      'label': '通信设备工程师',
    }, {
      'value': 101016,
      'label': '光通信工程师',
    }, {
      'value': 101017,
      'label': '光传输工程师',
    }, {
      'value': 101018,
      'label': '光网络工程师',
    }],
  }, {
    'value': 101400,
    'label': '电子/半导体',
    'children': [{
      'value': 101401,
      'label': '电子工程师',
    }, {
      'value': 101402,
      'label': '电气工程师',
    }, {
      'value': 101403,
      'label': 'FAE',
    }, {
      'value': 101404,
      'label': '电气设计工程师',
    }],
  }, {
    'value': 100700,
    'label': '高端技术职位',
    'children': [{
      'value': 100701,
      'label': '技术经理',
    }, {
      'value': 100702,
      'label': '技术总监',
    }, {
      'value': 100703,
      'label': '测试经理',
    }, {
      'value': 100704,
      'label': '架构师',
    }, {
      'value': 100705,
      'label': 'CTO',
    }, {
      'value': 100706,
      'label': '运维总监',
    }, {
      'value': 100707,
      'label': '技术合伙人',
    }],
  }, {
    'value': 101300,
    'label': '人工智能',
    'children': [{
      'value': 101301,
      'label': '机器学习',
    }, {
      'value': 101302,
      'label': '深度学习',
    }, {
      'value': 101303,
      'label': '图像算法',
    }, {
      'value': 101304,
      'label': '图像处理',
    }, {
      'value': 101305,
      'label': '语音识别',
    }, {
      'value': 101306,
      'label': '图像识别',
    }, {
      'value': 101307,
      'label': '算法研究员',
    }],
  }, {
    'value': 101200,
    'label': '软件销售支持',
    'children': [{
      'value': 101201,
      'label': '售前工程师',
    }, {
      'value': 101202,
      'label': '售后工程师',
    }],
  }, {
    'value': 101100,
    'label': '其他技术职位',
    'children': [{
      'value': 101101,
      'label': '其他技术职位',
    }],
  }],
}, {
  'value': 110000,
  'label': '产品',
  'children': [{
    'value': 110100,
    'label': '产品经理',
    'children': [{
      'value': 110101,
      'label': '产品经理',
    }, {
      'value': 110102,
      'label': '网页产品经理',
    }, {
      'value': 110103,
      'label': '移动产品经理',
    }, {
      'value': 110104,
      'label': '产品助理',
    }, {
      'value': 110105,
      'label': '数据产品经理',
    }, {
      'value': 110106,
      'label': '电商产品经理',
    }, {
      'value': 110107,
      'label': '游戏策划',
    }, {
      'value': 110108,
      'label': '产品专员',
    }],
  }, {
    'value': 110300,
    'label': '高端产品职位',
    'children': [{
      'value': 110302,
      'label': '产品总监',
    }, {
      'value': 110303,
      'label': '游戏制作人',
    }, {
      'value': 110304,
      'label': '产品VP',
    }],
  }, {
    'value': 110400,
    'label': '其他产品职位',
    'children': [{
      'value': 110401,
      'label': '其他产品职位',
    }],
  }],
}, {
  'value': 120000,
  'label': '设计',
  'children': [{
    'value': 120100,
    'label': '视觉设计',
    'children': [{
      'value': 120101,
      'label': '视觉设计师',
    }, {
      'value': 120102,
      'label': '网页设计师',
    }, {
      'value': 120103,
      'label': 'Flash设计师',
    }, {
      'value': 120104,
      'label': 'APP设计师',
    }, {
      'value': 120105,
      'label': 'UI设计师',
    }, {
      'value': 120106,
      'label': '平面设计师',
    }, {
      'value': 120107,
      'label': '美术设计师（2D/3D）',
    }, {
      'value': 120108,
      'label': '广告设计师',
    }, {
      'value': 120109,
      'label': '多媒体设计师',
    }, {
      'value': 120110,
      'label': '原画师',
    }, {
      'value': 120111,
      'label': '游戏特效',
    }, {
      'value': 120112,
      'label': '游戏界面设计师',
    }, {
      'value': 120113,
      'label': '游戏场景',
    }, {
      'value': 120114,
      'label': '游戏角色',
    }, {
      'value': 120115,
      'label': '游戏动作',
    }, {
      'value': 120116,
      'label': '三维/CAD/制图',
    }, {
      'value': 120117,
      'label': '美工',
    }, {
      'value': 120118,
      'label': '包装设计',
    }, {
      'value': 120119,
      'label': '设计师助理',
    }, {
      'value': 120120,
      'label': '动画设计师',
    }, {
      'value': 120121,
      'label': '插画师',
    }],
  }, {
    'value': 120200,
    'label': '交互设计',
    'children': [{
      'value': 120201,
      'label': '交互设计师',
    }, {
      'value': 120202,
      'label': '无线交互设计师',
    }, {
      'value': 120203,
      'label': '网页交互设计师',
    }, {
      'value': 120204,
      'label': '硬件交互设计师',
    }],
  }, {
    'value': 120300,
    'label': '用户研究',
    'children': [{
      'value': 120301,
      'label': '数据分析师',
    }, {
      'value': 120302,
      'label': '用户研究员',
    }, {
      'value': 120303,
      'label': '游戏数值策划',
    }, {
      'value': 120304,
      'label': 'UX设计师',
    }, {
      'value': 120407,
      'label': '用户研究经理',
    }, {
      'value': 120408,
      'label': '用户研究总监',
    }],
  }, {
    'value': 120400,
    'label': '高端设计职位',
    'children': [{
      'value': 120401,
      'label': '设计经理/主管',
    }, {
      'value': 120402,
      'label': '设计总监',
    }, {
      'value': 120403,
      'label': '视觉设计经理',
    }, {
      'value': 120404,
      'label': '视觉设计总监',
    }, {
      'value': 120405,
      'label': '交互设计经理/主管',
    }, {
      'value': 120406,
      'label': '交互设计总监',
    }],
  }, {
    'value': 120600,
    'label': '非视觉设计',
    'children': [{
      'value': 120601,
      'label': '服装设计',
    }, {
      'value': 120602,
      'label': '工业设计',
    }, {
      'value': 120603,
      'label': '橱柜设计',
    }, {
      'value': 120604,
      'label': '家具设计',
    }, {
      'value': 120605,
      'label': '家居设计',
    }, {
      'value': 120606,
      'label': '珠宝设计',
    }, {
      'value': 120607,
      'label': '室内设计',
    }, {
      'value': 120608,
      'label': '陈列设计',
    }, {
      'value': 120610,
      'label': '景观设计',
    }],
  }, {
    'value': 120500,
    'label': '其他设计职位',
    'children': [{
      'value': 120501,
      'label': '其他设计职位',
    }],
  }],
}, {
  'value': 130000,
  'label': '运营',
  'children': [{
    'value': 130100,
    'label': '运营',
    'children': [{
      'value': 130101,
      'label': '用户运营',
    }, {
      'value': 130102,
      'label': '产品运营',
    }, {
      'value': 130103,
      'label': '数据运营',
    }, {
      'value': 130104,
      'label': '内容运营',
    }, {
      'value': 130105,
      'label': '活动运营',
    }, {
      'value': 130106,
      'label': '商家运营',
    }, {
      'value': 130107,
      'label': '品类运营',
    }, {
      'value': 130108,
      'label': '游戏运营',
    }, {
      'value': 130109,
      'label': '网络推广',
    }, {
      'value': 130110,
      'label': '网站运营',
    }, {
      'value': 130111,
      'label': '新媒体运营',
    }, {
      'value': 130112,
      'label': '社区运营',
    }, {
      'value': 130113,
      'label': '微信运营',
    }, {
      'value': 130114,
      'label': '微博运营',
    }, {
      'value': 130115,
      'label': '策略运营',
    }, {
      'value': 130116,
      'label': '线下拓展运营',
    }, {
      'value': 130117,
      'label': '电商运营',
    }, {
      'value': 130118,
      'label': '运营助理/专员',
    }, {
      'value': 130120,
      'label': '内容审核',
    }, {
      'value': 130119,
      'label': '销售运营',
    }],
  }, {
    'value': 130200,
    'label': '编辑',
    'children': [{
      'value': 130201,
      'label': '副主编',
    }, {
      'value': 130202,
      'label': '内容编辑',
    }, {
      'value': 130203,
      'label': '文案策划',
    }, {
      'value': 130204,
      'label': '网站编辑',
    }, {
      'value': 130205,
      'label': '记者',
    }, {
      'value': 130206,
      'label': '采编',
    }],
  }, {
    'value': 130300,
    'label': '客服',
    'children': [{
      'value': 130301,
      'label': '售前咨询',
    }, {
      'value': 130302,
      'label': '售后咨询',
    }, {
      'value': 130303,
      'label': '网络客服',
    }, {
      'value': 130304,
      'label': '客服经理',
    }, {
      'value': 130305,
      'label': '客服专员/助理',
    }, {
      'value': 130306,
      'label': '客服主管',
    }, {
      'value': 130307,
      'label': '客服总监',
    }, {
      'value': 130308,
      'label': '电话客服',
    }, {
      'value': 130309,
      'label': '咨询热线/呼叫中心客服',
    }],
  }, {
    'value': 130400,
    'label': '高端运营职位',
    'children': [{
      'value': 130401,
      'label': '主编',
    }, {
      'value': 130402,
      'label': '运营总监',
    }, {
      'value': 130403,
      'label': 'COO',
    }, {
      'value': 130404,
      'label': '客服总监',
    }, {
      'value': 130405,
      'label': '运营经理/主管',
    }],
  }, {
    'value': 130500,
    'label': '其他运营职位',
    'children': [{
      'value': 130501,
      'label': '其他运营职位',
    }],
  }],
}, {
  'value': 140000,
  'label': '市场',
  'children': [{
    'value': 140100,
    'label': '市场/营销',
    'children': [{
      'value': 140114,
      'label': '选址开发',
    }, {
      'value': 140101,
      'label': '市场营销',
    }, {
      'value': 140102,
      'label': '市场策划',
    }, {
      'value': 140103,
      'label': '市场顾问',
    }, {
      'value': 140104,
      'label': '市场推广',
    }, {
      'value': 140105,
      'label': 'SEO',
    }, {
      'value': 140106,
      'label': 'SEM',
    }, {
      'value': 140107,
      'label': '商务渠道',
    }, {
      'value': 140108,
      'label': '商业数据分析',
    }, {
      'value': 140109,
      'label': '活动策划',
    }, {
      'value': 140110,
      'label': '网络营销',
    }, {
      'value': 140111,
      'label': '海外市场',
    }, {
      'value': 140112,
      'label': '政府关系',
    }, {
      'value': 140113,
      'label': 'APP推广',
    }],
  }, {
    'value': 140200,
    'label': '公关媒介',
    'children': [{
      'value': 140201,
      'label': '媒介经理',
    }, {
      'value': 140202,
      'label': '广告协调',
    }, {
      'value': 140203,
      'label': '品牌公关',
    }, {
      'value': 140204,
      'label': '媒介专员',
    }, {
      'value': 140205,
      'label': '活动策划执行',
    }, {
      'value': 140206,
      'label': '媒介策划',
    }],
  }, {
    'value': 140500,
    'label': '会务会展',
    'children': [{
      'value': 140501,
      'label': '会议活动销售',
    }, {
      'value': 140502,
      'label': '会议活动策划',
    }, {
      'value': 140503,
      'label': '会议活动执行',
    }, {
      'value': 140504,
      'label': '会展活动销售',
    }, {
      'value': 140505,
      'label': '会展活动策划',
    }, {
      'value': 140506,
      'label': '会展活动执行',
    }],
  }, {
    'value': 140600,
    'label': '广告',
    'children': [{
      'value': 140601,
      'label': '广告创意',
    }, {
      'value': 140602,
      'label': '美术指导',
    }, {
      'value': 140603,
      'label': '广告设计师',
    }, {
      'value': 140604,
      'label': '策划经理',
    }, {
      'value': 140605,
      'label': '文案',
    }, {
      'value': 140607,
      'label': '广告制作',
    }, {
      'value': 140608,
      'label': '媒介投放',
    }, {
      'value': 140609,
      'label': '媒介合作',
    }, {
      'value': 140610,
      'label': '媒介顾问',
    }, {
      'value': 140611,
      'label': '广告审核',
    }],
  }, {
    'value': 140400,
    'label': '高端市场职位',
    'children': [{
      'value': 140401,
      'label': '市场总监',
    }, {
      'value': 140404,
      'label': 'CMO',
    }, {
      'value': 140405,
      'label': '公关总监',
    }, {
      'value': 140406,
      'label': '媒介总监',
    }, {
      'value': 140407,
      'label': '创意总监',
    }],
  }, {
    'value': 140700,
    'label': '其他市场职位',
    'children': [{
      'value': 140701,
      'label': '其他市场职位',
    }],
  }],
}, {
  'value': 160000,
  'label': '销售',
  'children': [{
    'value': 140300,
    'label': '销售',
    'children': [{
      'value': 140301,
      'label': '销售专员',
    }, {
      'value': 140302,
      'label': '销售经理',
    }, {
      'value': 140303,
      'label': '客户代表',
    }, {
      'value': 140304,
      'label': '大客户代表',
    }, {
      'value': 140305,
      'label': 'BD经理',
    }, {
      'value': 140306,
      'label': '商务渠道',
    }, {
      'value': 140307,
      'label': '渠道销售',
    }, {
      'value': 140308,
      'label': '代理商销售',
    }, {
      'value': 140309,
      'label': '销售助理',
    }, {
      'value': 140310,
      'label': '电话销售',
    }, {
      'value': 140311,
      'label': '销售顾问',
    }, {
      'value': 140312,
      'label': '商品经理',
    }, {
      'value': 140313,
      'label': '广告销售',
    }, {
      'value': 140314,
      'label': '网络营销',
    }, {
      'value': 140315,
      'label': '营销主管',
    }, {
      'value': 140316,
      'label': '销售工程师',
    }, {
      'value': 140317,
      'label': '客户经理',
    }],
  }, {
    'value': 160100,
    'label': '销售管理',
    'children': [{
      'value': 140402,
      'label': '销售总监',
    }, {
      'value': 140403,
      'label': '商务总监',
    }, {
      'value': 160101,
      'label': '区域总监',
    }, {
      'value': 160102,
      'label': '城市经理',
    }, {
      'value': 160103,
      'label': '销售VP',
    }, {
      'value': 160104,
      'label': '团队经理',
    }],
  }, {
    'value': 160200,
    'label': '其他销售职位',
    'children': [{
      'value': 160201,
      'label': '其他销售职位',
    }],
  }],
}, {
  'value': 150000,
  'label': '人事/财务/行政',
  'children': [{
    'value': 150100,
    'label': '人力资源',
    'children': [{
      'value': 150101,
      'label': '人力资源主管',
    }, {
      'value': 150102,
      'label': '招聘',
    }, {
      'value': 150103,
      'label': 'HRBP',
    }, {
      'value': 150104,
      'label': '人力资源专员/助理',
    }, {
      'value': 150105,
      'label': '培训',
    }, {
      'value': 150106,
      'label': '薪资福利',
    }, {
      'value': 150107,
      'label': '绩效考核',
    }, {
      'value': 150403,
      'label': '人力资源经理',
    }, {
      'value': 150406,
      'label': '人力资源VP/CHO',
    }, {
      'value': 150108,
      'label': '人力资源总监',
    }, {
      'value': 150109,
      'label': '员工关系',
    }, {
      'value': 150110,
      'label': '组织发展',
    }],
  }, {
    'value': 150200,
    'label': '行政',
    'children': [{
      'value': 150201,
      'label': '行政专员/助理',
    }, {
      'value': 150202,
      'label': '前台',
    }, {
      'value': 150204,
      'label': '行政主管',
    }, {
      'value': 150205,
      'label': '经理助理',
    }, {
      'value': 150207,
      'label': '后勤',
    }, {
      'value': 150208,
      'label': '商务司机',
    }, {
      'value': 150401,
      'label': '行政经理',
    }, {
      'value': 150209,
      'label': '行政总监',
    }],
  }, {
    'value': 150300,
    'label': '财务',
    'children': [{
      'value': 150301,
      'label': '会计',
    }, {
      'value': 150302,
      'label': '出纳',
    }, {
      'value': 150303,
      'label': '财务顾问',
    }, {
      'value': 150304,
      'label': '结算',
    }, {
      'value': 150305,
      'label': '税务',
    }, {
      'value': 150306,
      'label': '审计',
    }, {
      'value': 150307,
      'label': '风控',
    }, {
      'value': 150402,
      'label': '财务经理',
    }, {
      'value': 150404,
      'label': 'CFO',
    }, {
      'value': 150308,
      'label': '财务总监',
    }, {
      'value': 150309,
      'label': '财务主管',
    }],
  }, {
    'value': 150500,
    'label': '法务',
    'children': [{
      'value': 150203,
      'label': '法务专员/助理',
    }, {
      'value': 150502,
      'label': '律师',
    }, {
      'value': 150503,
      'label': '专利',
    }, {
      'value': 150504,
      'label': '法律顾问',
    }, {
      'value': 150505,
      'label': '法务主管',
    }, {
      'value': 150506,
      'label': '法务经理',
    }, {
      'value': 150507,
      'label': '法务总监',
    }],
  }, {
    'value': 150600,
    'label': '其他职能职位',
    'children': [{
      'value': 150601,
      'label': '其他职能职位',
    }],
  }],
}, {
  'value': 310000,
  'label': '高级管理',
  'children': [{
    'value': 150400,
    'label': '高级管理职位',
    'children': [{
      'value': 150407,
      'label': 'CEO/总裁/总经理',
    }, {
      'value': 150408,
      'label': '副总裁/副总经理',
    }, {
      'value': 150409,
      'label': '事业部负责人',
    }, {
      'value': 150410,
      'label': '区域/分公司/代表处负责人',
    }, {
      'value': 150411,
      'label': '总裁/总经理/董事长助理',
    }, {
      'value': 150412,
      'label': '合伙人',
    }, {
      'value': 150413,
      'label': '创始人',
    }, {
      'value': 150414,
      'label': '董事会秘书',
    }],
  }],
}, {
  'value': 170000,
  'label': '传媒',
  'children': [{
    'value': 170100,
    'label': '采编/写作/出版',
    'children': [{
      'value': 170101,
      'label': '记者',
    }, {
      'value': 170102,
      'label': '编辑',
    }, {
      'value': 170103,
      'label': '采编',
    }, {
      'value': 170104,
      'label': '撰稿人',
    }, {
      'value': 170105,
      'label': '出版发行',
    }, {
      'value': 170106,
      'label': '校对录入',
    }, {
      'value': 170107,
      'label': '总编',
    }, {
      'value': 170108,
      'label': '自媒体',
    }],
  }, {
    'value': 170300,
    'label': '公关媒介',
    'children': [{
      'value': 170301,
      'label': '媒介经理',
    }, {
      'value': 170302,
      'label': '媒介专员',
    }, {
      'value': 170303,
      'label': '广告协调',
    }, {
      'value': 170304,
      'label': '品牌公关',
    }, {
      'value': 170305,
      'label': '活动策划执行',
    }, {
      'value': 170306,
      'label': '媒介策划',
    }],
  }, {
    'value': 170400,
    'label': '会务会展',
    'children': [{
      'value': 170401,
      'label': '会议活动销售',
    }, {
      'value': 170402,
      'label': '会议活动策划',
    }, {
      'value': 170403,
      'label': '会议活动执行',
    }, {
      'value': 170404,
      'label': '会展活动销售',
    }, {
      'value': 170405,
      'label': '会展活动策划',
    }, {
      'value': 170406,
      'label': '会展活动执行',
    }],
  }, {
    'value': 170200,
    'label': '广告',
    'children': [{
      'value': 170201,
      'label': '广告创意',
    }, {
      'value': 170202,
      'label': '美术指导',
    }, {
      'value': 170203,
      'label': '广告设计师',
    }, {
      'value': 170204,
      'label': '策划经理',
    }, {
      'value': 170205,
      'label': '文案',
    }, {
      'value': 170207,
      'label': '广告制作',
    }, {
      'value': 170208,
      'label': '媒介投放',
    }, {
      'value': 170209,
      'label': '媒介合作',
    }, {
      'value': 170210,
      'label': '媒介顾问',
    }, {
      'value': 170211,
      'label': '广告审核',
    }],
  }, {
    'value': 170600,
    'label': '影视媒体',
    'children': [{
      'value': 170617,
      'label': '助理',
    }, {
      'value': 170618,
      'label': '统筹制片人',
    }, {
      'value': 170619,
      'label': '执行制片人',
    }, {
      'value': 170601,
      'label': '导演/编导',
    }, {
      'value': 170602,
      'label': '摄影/影像师',
    }, {
      'value': 170603,
      'label': '视频编辑',
    }, {
      'value': 170604,
      'label': '音频编辑',
    }, {
      'value': 170605,
      'label': '经纪人',
    }, {
      'value': 170606,
      'label': '后期制作',
    }, {
      'value': 170607,
      'label': '影视制作',
    }, {
      'value': 170608,
      'label': '影视发行',
    }, {
      'value': 170609,
      'label': '影视策划',
    }, {
      'value': 170610,
      'label': '主持人/主播/DJ',
    }, {
      'value': 170611,
      'label': '演员/配音/模特',
    }, {
      'value': 170612,
      'label': '化妆/造型/服装',
    }, {
      'value': 170613,
      'label': '放映管理',
    }, {
      'value': 170614,
      'label': '录音/音效',
    }, {
      'value': 170615,
      'label': '制片人',
    }, {
      'value': 170616,
      'label': '编剧',
    }],
  }, {
    'value': 170500,
    'label': '其他传媒职位',
    'children': [{
      'value': 170501,
      'label': '其他传媒职位',
    }],
  }],
}, {
  'value': 180000,
  'label': '金融',
  'children': [{
    'value': 180100,
    'label': '投融资',
    'children': [{
      'value': 180101,
      'label': '投资经理',
    }, {
      'value': 180103,
      'label': '行业研究',
    }, {
      'value': 180104,
      'label': '资产管理',
    }, {
      'value': 180112,
      'label': '投资总监',
    }, {
      'value': 180113,
      'label': '投资VP',
    }, {
      'value': 180114,
      'label': '投资合伙人',
    }, {
      'value': 180115,
      'label': '融资',
    }, {
      'value': 180116,
      'label': '并购',
    }, {
      'value': 180117,
      'label': '投后管理',
    }, {
      'value': 180118,
      'label': '投资助理',
    }, {
      'value': 180111,
      'label': '其他投融资职位',
    }, {
      'value': 180119,
      'label': '投资顾问',
    }],
  }, {
    'value': 180200,
    'label': '风控',
    'children': [{
      'value': 180201,
      'label': '风控',
    }, {
      'value': 180202,
      'label': '律师',
    }, {
      'value': 180203,
      'label': '资信评估',
    }, {
      'value': 180204,
      'label': '合规稽查',
    }],
  }, {
    'value': 180300,
    'label': '税务审计',
    'children': [{
      'value': 180301,
      'label': '审计',
    }, {
      'value': 180302,
      'label': '法务',
    }, {
      'value': 180303,
      'label': '会计',
    }, {
      'value': 180304,
      'label': '清算',
    }],
  }, {
    'value': 180400,
    'label': '银行',
    'children': [{
      'value': 180401,
      'label': '信用卡销售',
    }, {
      'value': 180102,
      'label': '分析师',
    }, {
      'value': 180402,
      'label': '柜员',
    }, {
      'value': 180403,
      'label': '商务渠道',
    }, {
      'value': 180404,
      'label': '大堂经理',
    }, {
      'value': 180105,
      'label': '理财顾问',
    }, {
      'value': 180405,
      'label': '客户经理',
    }, {
      'value': 180406,
      'label': '信贷管理',
    }, {
      'value': 180107,
      'label': '风控',
    }],
  }, {
    'value': 180500,
    'label': '互联网金融',
    'children': [{
      'value': 180501,
      'label': '金融产品经理',
    }, {
      'value': 180502,
      'label': '风控',
    }, {
      'value': 180503,
      'label': '催收员',
    }, {
      'value': 180504,
      'label': '分析师',
    }, {
      'value': 180505,
      'label': '投资经理',
    }, {
      'value': 180106,
      'label': '交易员',
    }, {
      'value': 180506,
      'label': '理财顾问',
    }, {
      'value': 180108,
      'label': '合规稽查',
    }, {
      'value': 180109,
      'label': '审计',
    }, {
      'value': 180110,
      'label': '清算',
    }],
  }, {
    'value': 180700,
    'label': '保险',
    'children': [{
      'value': 180701,
      'label': '保险业务',
    }, {
      'value': 180702,
      'label': '精算师',
    }, {
      'value': 180703,
      'label': '保险理赔',
    }],
  }, {
    'value': 180600,
    'label': '其他金融职位',
    'children': [{
      'value': 180601,
      'label': '其他金融职位',
    }],
  }, {
    'value': 180800,
    'label': '证券',
    'children': [{
      'value': 180801,
      'label': '证券经纪人',
    }, {
      'value': 180802,
      'label': '证券分析师',
    }],
  }],
}, {
  'value': 230000,
  'label': '汽车',
  'children': [{
    'value': 230100,
    'label': '汽车设计与研发',
    'children': [{
      'value': 230101,
      'label': '汽车设计',
    }, {
      'value': 230102,
      'label': '车身设计',
    }, {
      'value': 230103,
      'label': '底盘设计',
    }, {
      'value': 230104,
      'label': '机械设计',
    }, {
      'value': 230105,
      'label': '动力系统设计',
    }, {
      'value': 230106,
      'label': '电子工程设计',
    }, {
      'value': 230107,
      'label': '零部件设计',
    }, {
      'value': 230108,
      'label': '汽车工程项目管理',
    }, {
      'value': 230110,
      'label': '内外饰设计工程师',
    }],
  }, {
    'value': 230400,
    'label': '汽车生产与制造',
    'children': [{
      'value': 230210,
      'label': '总装工程师',
    }, {
      'value': 230211,
      'label': '焊接工程师',
    }, {
      'value': 230212,
      'label': '冲压工程师',
    }, {
      'value': 230109,
      'label': '质量工程师',
    }],
  }, {
    'value': 230200,
    'label': '汽车销售与服务',
    'children': [{
      'value': 230201,
      'label': '汽车销售',
    }, {
      'value': 230202,
      'label': '汽车配件销售',
    }, {
      'value': 230203,
      'label': '汽车售后服务',
    }, {
      'value': 230204,
      'label': '汽车维修',
    }, {
      'value': 230205,
      'label': '汽车美容',
    }, {
      'value': 230206,
      'label': '汽车定损理赔',
    }, {
      'value': 230207,
      'label': '二手车评估师',
    }, {
      'value': 230208,
      'label': '4S店管理',
    }, {
      'value': 230209,
      'label': '汽车改装工程师',
    }],
  }, {
    'value': 230300,
    'label': '其他汽车职位',
    'children': [{
      'value': 230301,
      'label': '其他汽车职位',
    }],
  }],
}, {
  'value': 190000,
  'label': '教育培训',
  'children': [{
    'value': 190100,
    'label': '教育产品研发',
    'children': [{
      'value': 190101,
      'label': '课程设计',
    }, {
      'value': 190102,
      'label': '课程编辑',
    }, {
      'value': 190103,
      'label': '教师',
    }, {
      'value': 190104,
      'label': '培训研究',
    }, {
      'value': 190105,
      'label': '培训师',
    }, {
      'value': 190107,
      'label': '培训策划',
    }, {
      'value': 190106,
      'label': '其他教育产品研发职位',
    }],
  }, {
    'value': 190200,
    'label': '教育行政',
    'children': [{
      'value': 190201,
      'label': '校长',
    }, {
      'value': 190202,
      'label': '教务管理',
    }, {
      'value': 190203,
      'label': '教学管理',
    }, {
      'value': 190204,
      'label': '班主任/辅导员',
    }],
  }, {
    'value': 190300,
    'label': '教师',
    'children': [{
      'value': 190301,
      'label': '教师',
    }, {
      'value': 190302,
      'label': '助教',
    }, {
      'value': 190303,
      'label': '高中教师',
    }, {
      'value': 190304,
      'label': '初中教师',
    }, {
      'value': 190305,
      'label': '小学教师',
    }, {
      'value': 190306,
      'label': '幼教',
    }, {
      'value': 190307,
      'label': '理科教师',
    }, {
      'value': 190308,
      'label': '文科教师',
    }, {
      'value': 190309,
      'label': '外语教师',
    }, {
      'value': 190310,
      'label': '音乐教师',
    }, {
      'value': 190311,
      'label': '美术教师',
    }, {
      'value': 190312,
      'label': '体育教师',
    }, {
      'value': 190313,
      'label': '就业老师',
    }],
  }, {
    'value': 190400,
    'label': 'IT培训',
    'children': [{
      'value': 190401,
      'label': 'JAVA培训讲师',
    }, {
      'value': 190402,
      'label': 'Androvalue培训讲师',
    }, {
      'value': 190403,
      'label': 'ios培训讲师',
    }, {
      'value': 190404,
      'label': 'PHP培训讲师',
    }, {
      'value': 190405,
      'label': '.NET培训讲师',
    }, {
      'value': 190406,
      'label': 'C++培训讲师',
    }, {
      'value': 190407,
      'label': 'Unity 3D培训讲师',
    }, {
      'value': 190408,
      'label': 'Web前端培训讲师',
    }, {
      'value': 190409,
      'label': '软件测试培训讲师',
    }, {
      'value': 190410,
      'label': '动漫培训讲师',
    }, {
      'value': 190411,
      'label': 'UI设计培训讲师',
    }],
  }, {
    'value': 190500,
    'label': '职业培训',
    'children': [{
      'value': 190501,
      'label': '财会培训讲师',
    }, {
      'value': 190502,
      'label': 'HR培训讲师',
    }, {
      'value': 190503,
      'label': '培训师',
    }, {
      'value': 190504,
      'label': '拓展培训',
    }],
  }, {
    'value': 190600,
    'label': '招生',
    'children': [{
      'value': 190601,
      'label': '课程顾问',
    }, {
      'value': 190602,
      'label': '招生顾问',
    }, {
      'value': 190603,
      'label': '留学顾问',
    }],
  }, {
    'value': 190700,
    'label': '教练',
    'children': [{
      'value': 190701,
      'label': '舞蹈教练',
    }, {
      'value': 190702,
      'label': '瑜伽教练',
    }, {
      'value': 190703,
      'label': '瘦身顾问',
    }, {
      'value': 190704,
      'label': '游泳教练',
    }, {
      'value': 190705,
      'label': '健身教练',
    }, {
      'value': 190706,
      'label': '篮球/羽毛球教练',
    }, {
      'value': 190707,
      'label': '跆拳道教练',
    }],
  }, {
    'value': 190800,
    'label': '其他教育培训职位',
    'children': [{
      'value': 190801,
      'label': '其他教育培训职位',
    }],
  }],
}, {
  'value': 210000,
  'label': '医疗健康',
  'children': [{
    'value': 210800,
    'label': '药店',
    'children': [{
      'value': 210801,
      'label': '店长',
    }, {
      'value': 210802,
      'label': '执业药师/驻店药师',
    }, {
      'value': 210803,
      'label': '店员/营业员',
    }],
  }, {
    'value': 210100,
    'label': '医疗技术',
    'children': [{
      'value': 210112,
      'label': '医生助理',
    }, {
      'value': 210113,
      'label': '医学影像',
    }, {
      'value': 210114,
      'label': 'B超医生',
    }, {
      'value': 210115,
      'label': '生物制药',
    }, {
      'value': 210116,
      'label': '药品注册',
    }, {
      'value': 210117,
      'label': '药品生产',
    }, {
      'value': 210118,
      'label': '临床研究',
    }, {
      'value': 210119,
      'label': '临床协调',
    }, {
      'value': 210120,
      'label': '临床数据分析',
    }, {
      'value': 210121,
      'label': '医疗器械注册',
    }, {
      'value': 210122,
      'label': '医疗器械生产/质量管理',
    }, {
      'value': 210101,
      'label': '医学编辑',
    }, {
      'value': 210102,
      'label': '药学编辑',
    }, {
      'value': 210103,
      'label': '医师',
    }, {
      'value': 210104,
      'label': '药剂师',
    }, {
      'value': 210105,
      'label': '医疗器械研究',
    }, {
      'value': 210106,
      'label': '医学总监',
    }, {
      'value': 210108,
      'label': '医药研发',
    }, {
      'value': 210109,
      'label': '验光师',
    }, {
      'value': 210110,
      'label': '放射科医师',
    }, {
      'value': 210111,
      'label': '检验科医师',
    }, {
      'value': 210107,
      'label': '其他医疗技术职位',
    }],
  }, {
    'value': 210200,
    'label': '护士/护理',
    'children': [{
      'value': 210202,
      'label': '护士长',
    }, {
      'value': 210201,
      'label': '护士/护理',
    }],
  }, {
    'value': 210300,
    'label': '医师/医生',
    'children': [{
      'value': 210301,
      'label': '医师',
    }, {
      'value': 210302,
      'label': '中医',
    }, {
      'value': 210303,
      'label': '心理医生',
    }, {
      'value': 210304,
      'label': '牙科医生',
    }, {
      'value': 210305,
      'label': '康复治疗师',
    }],
  }, {
    'value': 210400,
    'label': '健康整形',
    'children': [{
      'value': 210401,
      'label': '营养师',
    }, {
      'value': 210402,
      'label': '整形师',
    }, {
      'value': 210403,
      'label': '理疗师',
    }, {
      'value': 210404,
      'label': '针灸推拿',
    }, {
      'value': 210405,
      'label': '美容师/顾问',
    }],
  }, {
    'value': 210500,
    'label': '市场销售',
    'children': [{
      'value': 210506,
      'label': '医疗器械销售',
    }, {
      'value': 210501,
      'label': '医学总监',
    }, {
      'value': 210502,
      'label': '医药代表',
    }, {
      'value': 210503,
      'label': '导医',
    }, {
      'value': 210504,
      'label': '健康顾问',
    }, {
      'value': 210505,
      'label': '医美咨询',
    }],
  }, {
    'value': 210600,
    'label': '健身',
    'children': [{
      'value': 210601,
      'label': '瑜伽教练',
    }, {
      'value': 210602,
      'label': '瘦身顾问',
    }, {
      'value': 210603,
      'label': '游泳教练',
    }, {
      'value': 210604,
      'label': '美体教练',
    }, {
      'value': 210605,
      'label': '舞蹈教练',
    }, {
      'value': 210606,
      'label': '健身教练',
    }],
  }, {
    'value': 210700,
    'label': '其他医疗健康类职位',
    'children': [{
      'value': 210701,
      'label': '其他医疗健康类职位',
    }],
  }],
}, {
  'value': 250000,
  'label': '采购/贸易',
  'children': [{
    'value': 250100,
    'label': '采购',
    'children': [{
      'value': 250101,
      'label': '采购总监',
    }, {
      'value': 250102,
      'label': '采购经理',
    }, {
      'value': 250103,
      'label': '采购专员',
    }, {
      'value': 250104,
      'label': '买手',
    }, {
      'value': 250105,
      'label': '采购工程师',
    }, {
      'value': 250106,
      'label': '采购主管',
    }, {
      'value': 250107,
      'label': '采购助理',
    }],
  }, {
    'value': 250200,
    'label': '进出口贸易',
    'children': [{
      'value': 250201,
      'label': '外贸经理',
    }, {
      'value': 250202,
      'label': '外贸专员',
    }, {
      'value': 250203,
      'label': '外贸业务员',
    }, {
      'value': 250204,
      'label': '贸易跟单',
    }],
  }, {
    'value': 250300,
    'label': '其他采购/贸易职位',
    'children': [{
      'value': 250301,
      'label': '其他采购/贸易类职位',
    }],
  }],
}, {
  'value': 240000,
  'label': '供应链/物流',
  'children': [{
    'value': 240100,
    'label': '物流',
    'children': [{
      'value': 240101,
      'label': '供应链专员',
    }, {
      'value': 240102,
      'label': '供应链经理',
    }, {
      'value': 240103,
      'label': '物流专员',
    }, {
      'value': 240104,
      'label': '物流经理',
    }, {
      'value': 240105,
      'label': '物流运营',
    }, {
      'value': 240106,
      'label': '物流跟单',
    }, {
      'value': 240107,
      'label': '贸易跟单',
    }, {
      'value': 240108,
      'label': '物仓调度',
    }, {
      'value': 240109,
      'label': '物仓项目',
    }, {
      'value': 240110,
      'label': '运输经理/主管',
    }, {
      'value': 240111,
      'label': '货运代理专员',
    }, {
      'value': 240112,
      'label': '货运代理经理',
    }, {
      'value': 240113,
      'label': '水/空/陆运操作',
    }, {
      'value': 240114,
      'label': '报关员',
    }, {
      'value': 240115,
      'label': '报检员',
    }, {
      'value': 240116,
      'label': '核销员',
    }, {
      'value': 240117,
      'label': '单证员',
    }],
  }, {
    'value': 240200,
    'label': '仓储',
    'children': [{
      'value': 240201,
      'label': '仓储物料经理',
    }, {
      'value': 240202,
      'label': '仓储物料专员',
    }, {
      'value': 240203,
      'label': '仓储物料项目',
    }, {
      'value': 240204,
      'label': '仓储管理',
    }, {
      'value': 240205,
      'label': '仓库文员',
    }, {
      'value': 240206,
      'label': '配/理/拣/发货',
    }],
  }, {
    'value': 240300,
    'label': '运输',
    'children': [{
      'value': 240301,
      'label': '货运司机',
    }, {
      'value': 240302,
      'label': '集装箱管理',
    }, {
      'value': 240303,
      'label': '配送',
    }, {
      'value': 240304,
      'label': '快递',
    }],
  }, {
    'value': 240400,
    'label': '高端供应链职位',
    'children': [{
      'value': 240401,
      'label': '供应链总监',
    }, {
      'value': 240402,
      'label': '物流总监',
    }],
  }, {
    'value': 240500,
    'label': '其他供应链职位',
    'children': [{
      'value': 240501,
      'label': '其他供应链职位',
    }],
  }],
}, {
  'value': 220000,
  'label': '房地产/建筑',
  'children': [{
    'value': 220100,
    'label': '房地产规划开发',
    'children': [{
      'value': 220101,
      'label': '房产策划',
    }, {
      'value': 220102,
      'label': '地产项目管理',
    }, {
      'value': 220103,
      'label': '地产招投标',
    }],
  }, {
    'value': 220200,
    'label': '设计装修与市政建设',
    'children': [{
      'value': 220201,
      'label': '高级建筑工程师',
    }, {
      'value': 220202,
      'label': '建筑工程师',
    }, {
      'value': 220203,
      'label': '建筑设计师',
    }, {
      'value': 220204,
      'label': '土木/土建/结构工程师',
    }, {
      'value': 220205,
      'label': '室内设计',
    }, {
      'value': 220206,
      'label': '园林设计',
    }, {
      'value': 220207,
      'label': '城市规划设计',
    }, {
      'value': 220208,
      'label': '工程监理',
    }, {
      'value': 220209,
      'label': '工程造价',
    }, {
      'value': 220210,
      'label': '预结算',
    }, {
      'value': 220211,
      'label': '工程资料管理',
    }, {
      'value': 220212,
      'label': '建筑施工现场管理',
    }],
  }, {
    'value': 220300,
    'label': '房地产经纪',
    'children': [{
      'value': 220301,
      'label': '地产置业顾问',
    }, {
      'value': 220302,
      'label': '地产评估',
    }, {
      'value': 220303,
      'label': '地产中介',
    }],
  }, {
    'value': 220400,
    'label': '物业管理',
    'children': [{
      'value': 220401,
      'label': '物业管理',
    }, {
      'value': 220402,
      'label': '物业租赁销售 ',
    }, {
      'value': 220403,
      'label': '物业招商管理',
    }],
  }, {
    'value': 220500,
    'label': '高端房地产职位',
    'children': [{
      'value': 220501,
      'label': '地产项目总监',
    }, {
      'value': 220502,
      'label': '地产策划总监',
    }, {
      'value': 220503,
      'label': '地产招投标总监',
    }, {
      'value': 220504,
      'label': '物业总监',
    }, {
      'value': 220505,
      'label': '房地产销售总监',
    }],
  }, {
    'value': 220600,
    'label': '其他房地产职位',
    'children': [{
      'value': 220601,
      'label': '其他房地产职位',
    }],
  }],
}, {
  'value': 260000,
  'label': '咨询/翻译/法律',
  'children': [{
    'value': 260100,
    'label': '咨询/调研',
    'children': [{
      'value': 260101,
      'label': '企业管理咨询',
    }, {
      'value': 260102,
      'label': '数据分析师',
    }, {
      'value': 260103,
      'label': '财务咨询顾问',
    }, {
      'value': 260104,
      'label': 'IT咨询顾问',
    }, {
      'value': 260105,
      'label': '人力资源顾问',
    }, {
      'value': 260106,
      'label': '咨询项目管理',
    }, {
      'value': 260107,
      'label': '战略咨询',
    }, {
      'value': 260108,
      'label': '猎头顾问',
    }, {
      'value': 260109,
      'label': '市场调研',
    }, {
      'value': 260110,
      'label': '其他咨询顾问',
    }],
  }, {
    'value': 260200,
    'label': '律师',
    'children': [{
      'value': 260203,
      'label': '知识产权',
    }, {
      'value': 260201,
      'label': '事务所律师',
    }, {
      'value': 260202,
      'label': '公司法务',
    }],
  }, {
    'value': 260300,
    'label': '翻译',
    'children': [{
      'value': 260301,
      'label': '英语翻译',
    }, {
      'value': 260302,
      'label': '日语翻译',
    }, {
      'value': 260303,
      'label': '韩语/朝鲜语翻译',
    }, {
      'value': 260304,
      'label': '法语翻译',
    }, {
      'value': 260305,
      'label': '德语翻译',
    }, {
      'value': 260306,
      'label': '俄语翻译',
    }, {
      'value': 260307,
      'label': '西班牙语翻译',
    }, {
      'value': 260308,
      'label': '其他语种翻译',
    }],
  }, {
    'value': 260400,
    'label': '高端咨询类职位',
    'children': [{
      'value': 260401,
      'label': '咨询总监',
    }, {
      'value': 260402,
      'label': '咨询经理',
    }, {
      'value': 260403,
      'label': '高级翻译',
    }, {
      'value': 260404,
      'label': '同声传译 ',
    }],
  }, {
    'value': 260500,
    'label': '其他咨询类职位',
    'children': [{
      'value': 260501,
      'label': '其他咨询/翻译类职位',
    }],
  }],
}, {
  'value': 270000,
  'label': '实习生/管培生',
  'children': [{
    'value': 270100,
    'label': '实习生/培训生/储备干部',
    'children': [{
      'value': 270101,
      'label': '实习生',
    }, {
      'value': 270102,
      'label': '管理培训生',
    }, {
      'value': 270103,
      'label': '储备干部',
    }],
  }, {
    'value': 270200,
    'label': '其他实习/培训/储备职位',
    'children': [{
      'value': 270201,
      'label': '其他实习/培训/储备职位',
    }],
  }],
}, {
  'value': 280000,
  'label': '旅游',
  'children': [{
    'value': 280100,
    'label': '旅游服务',
    'children': [{
      'value': 280101,
      'label': '计调',
    }, {
      'value': 280102,
      'label': '签证',
    }, {
      'value': 280103,
      'label': '旅游顾问',
    }, {
      'value': 280104,
      'label': '导游',
    }, {
      'value': 280105,
      'label': '预定票务',
    }],
  }, {
    'value': 280200,
    'label': '旅游产品开发/策划',
    'children': [{
      'value': 280201,
      'label': '旅游产品经理',
    }, {
      'value': 280202,
      'label': '旅游策划师',
    }],
  }, {
    'value': 280300,
    'label': '其他旅游职位',
    'children': [{
      'value': 280301,
      'label': '其他旅游职位',
    }],
  }],
}, {
  'value': 290000,
  'label': '酒店/餐饮/零售',
  'children': [{
    'value': 290100,
    'label': '酒店',
    'children': [{
      'value': 290105,
      'label': '保安',
    }, {
      'value': 290106,
      'label': '保洁',
    }, {
      'value': 290101,
      'label': '收银',
    }, {
      'value': 290102,
      'label': '酒店前台',
    }, {
      'value': 290103,
      'label': '客房服务员',
    }, {
      'value': 290104,
      'label': '酒店经理',
    }],
  }, {
    'value': 290200,
    'label': '餐饮',
    'children': [{
      'value': 290201,
      'label': '收银',
    }, {
      'value': 290202,
      'label': '服务员',
    }, {
      'value': 290203,
      'label': '厨师',
    }, {
      'value': 290204,
      'label': '咖啡师',
    }, {
      'value': 290205,
      'label': '送餐员',
    }, {
      'value': 290206,
      'label': '餐饮店长',
    }, {
      'value': 290207,
      'label': '领班',
    }],
  }, {
    'value': 290300,
    'label': '零售',
    'children': [{
      'value': 290305,
      'label': '督导/巡店',
    }, {
      'value': 290301,
      'label': '收银',
    }, {
      'value': 290302,
      'label': '导购',
    }, {
      'value': 290303,
      'label': '店员/营业员',
    }, {
      'value': 290304,
      'label': '门店店长',
    }],
  }, {
    'value': 290400,
    'label': '其他酒店/餐饮/零售职位',
    'children': [{
      'value': 290401,
      'label': '其他酒店/餐饮/零售职位',
    }],
  }],
}, {
  'value': 300000,
  'label': '生产制造',
  'children': [{
    'value': 300100,
    'label': '生产营运',
    'children': [{
      'value': 300101,
      'label': '厂长/工厂经理',
    }, {
      'value': 300102,
      'label': '生产总监',
    }, {
      'value': 300103,
      'label': '生产经理/车间主任',
    }, {
      'value': 300104,
      'label': '生产组长/拉长',
    }, {
      'value': 300105,
      'label': '生产员',
    }, {
      'value': 300106,
      'label': '生产设备管理',
    }, {
      'value': 300107,
      'label': '生产计划/物料控制',
    }, {
      'value': 300108,
      'label': '生产跟单',
    }],
  }, {
    'value': 300200,
    'label': '质量安全',
    'children': [{
      'value': 300201,
      'label': '质量管理/测试',
    }, {
      'value': 300202,
      'label': '可靠度工程师',
    }, {
      'value': 300203,
      'label': '故障分析师',
    }, {
      'value': 300204,
      'label': '认证工程师',
    }, {
      'value': 300205,
      'label': '体系工程师',
    }, {
      'value': 300206,
      'label': '审核员',
    }, {
      'value': 300207,
      'label': '安全员',
    }],
  }, {
    'value': 300300,
    'label': '机械设计/制造',
    'children': [{
      'value': 300301,
      'label': '机械工程师',
    }, {
      'value': 300302,
      'label': '机械设计师',
    }, {
      'value': 300303,
      'label': '机械设备工程师',
    }, {
      'value': 300304,
      'label': '机械维修/保养',
    }, {
      'value': 300305,
      'label': '机械制图',
    }, {
      'value': 300306,
      'label': '机械结构工程师',
    }, {
      'value': 300307,
      'label': '工业工程师',
    }, {
      'value': 300308,
      'label': '工艺/制程工程师',
    }, {
      'value': 300309,
      'label': '材料工程师',
    }, {
      'value': 300310,
      'label': '机电工程师',
    }, {
      'value': 300311,
      'label': 'CNC/数控',
    }, {
      'value': 300312,
      'label': '冲压工程师',
    }, {
      'value': 300313,
      'label': '夹具工程师',
    }, {
      'value': 300314,
      'label': '模具工程师',
    }, {
      'value': 300315,
      'label': '焊接工程师',
    }, {
      'value': 300316,
      'label': '注塑工程师',
    }, {
      'value': 300317,
      'label': '铸造/锻造工程师',
    }],
  }, {
    'value': 300400,
    'label': '化工',
    'children': [{
      'value': 300401,
      'label': '化工工程师',
    }, {
      'value': 300402,
      'label': '实验室技术员',
    }, {
      'value': 300403,
      'label': '化学分析',
    }, {
      'value': 300404,
      'label': '涂料研发',
    }, {
      'value': 300405,
      'label': '化妆品研发',
    }, {
      'value': 300406,
      'label': '食品/饮料研发',
    }],
  }, {
    'value': 300500,
    'label': '服装/纺织/皮革',
    'children': [{
      'value': 300501,
      'label': '服装设计',
    }, {
      'value': 300502,
      'label': '女装设计',
    }, {
      'value': 300503,
      'label': '男装设计',
    }, {
      'value': 300504,
      'label': '童装设计',
    }, {
      'value': 300505,
      'label': '内衣设计',
    }, {
      'value': 300506,
      'label': '面料设计',
    }, {
      'value': 300507,
      'label': '面料辅料开发',
    }, {
      'value': 300508,
      'label': '面料辅料采购',
    }, {
      'value': 300509,
      'label': '打样/制版',
    }, {
      'value': 300510,
      'label': '服装/纺织/皮革跟单',
    }],
  }, {
    'value': 300600,
    'label': '技工/普工',
    'children': [{
      'value': 300601,
      'label': '普工/操作工',
    }, {
      'value': 300602,
      'label': '叉车',
    }, {
      'value': 300603,
      'label': '铲车',
    }, {
      'value': 300604,
      'label': '焊工',
    }, {
      'value': 300605,
      'label': '氩弧焊工',
    }, {
      'value': 300606,
      'label': '电工',
    }, {
      'value': 300608,
      'label': '木工',
    }, {
      'value': 300609,
      'label': '漆工',
    }, {
      'value': 300610,
      'label': '车工',
    }, {
      'value': 300611,
      'label': '磨工',
    }, {
      'value': 300612,
      'label': '铣工',
    }, {
      'value': 300613,
      'label': '钳工',
    }, {
      'value': 300614,
      'label': '钻工',
    }, {
      'value': 300615,
      'label': '铆工',
    }, {
      'value': 300616,
      'label': '钣金',
    }, {
      'value': 300617,
      'label': '抛光',
    }, {
      'value': 300618,
      'label': '机修工',
    }, {
      'value': 300619,
      'label': '折弯工',
    }, {
      'value': 300620,
      'label': '电镀工',
    }, {
      'value': 300621,
      'label': '喷塑工',
    }, {
      'value': 300622,
      'label': '注塑工',
    }, {
      'value': 300623,
      'label': '组装工',
    }, {
      'value': 300624,
      'label': '包装工',
    }, {
      'value': 300625,
      'label': '空调工',
    }, {
      'value': 300626,
      'label': '电梯工',
    }, {
      'value': 300627,
      'label': '锅炉工',
    }, {
      'value': 300628,
      'label': '学徒工',
    }],
  }, {
    'value': 300700,
    'label': '其他生产制造职位',
    'children': [{
      'value': 300701,
      'label': '其他生产制造职位',
    }],
  }],
}, {
  'value': 200000,
  'label': '其他',
  'children': [{
    'value': 200100,
    'label': '其他职位类别',
    'children': [{
      'value': 200101,
      'label': '其他职位',
    }],
  }],
}]

export default jobCategory
